package com.drrufus.lab1server.dao;

import com.drrufus.autogenerated.User;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class UserDao {
    
    private transient Logger logger = LoggerFactory.getLogger(UserDao.class);
    
    @Autowired
    JdbcTemplate jdbcTemplate;
    
    public User getUserById(Integer id) {
        logger.info("Retrieving user for id={}", id);
        String sql = "SELECT * FROM `users` WHERE `id` = ? ;";
        User user = (User)jdbcTemplate.queryForObject(sql, new UserRowMapper(), id);
        return user;
    }
    
    // for the next task
    public void insertUser(String login, String name, String email, String pass) {
        String sql = "insert into `users`(`name`, `email`, `login`, `pass`) values"
                + " (?, ?, ?, ?)";
        jdbcTemplate.update(sql, name, email, login, pass);
    }

    public List<User> getUserByParams(Integer id, String login, String name, String email, String pass) throws Exception {
        if (id != null && id == 0)
            id = null;
        logger.info("Retrieving users by id={}, login={}, name={}, email={}, pass={}",
                id, login, name, email, pass);
        
        if (id == null && login == null && name == null
                && email == null && pass == null)
            throw new Exception("No parameters for searching found");
        
        String sql = "SELECT * FROM `users` WHERE" +
                (id == null ? "" : (" `id` = " + id)) +
                (login == null ? "" : (" `login` = '" + login + "'")) +
                (name == null ? "" : (" `name` = '" + name + "'")) +
                (email == null ? "" : (" `email` = '" + email + "'")) +
                (pass == null ? "" : (" `pass` = '" + pass + "'"));
        logger.info("Generated SQL: {}", sql);
        List<User> users = jdbcTemplate.query(sql, new UserRowMapper());
        return users;
    }
}
